name: Crawl ITviec

on:
  workflow_dispatch:

  schedule:
    - cron: "0 1,5,9,13 * * *"

jobs:

  crawl:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run crawler
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python crawler/crawl_ITjob.py
          python etl/load.py